targets:
  $default:
    builders:
      injectable_generator|injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - packages/core/network/lib/**.dart

      injectable_generator|injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - packages/core/network/lib/**.dart
