name: injectable_poc
description: A new Flutter project.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.3.0
  mocktail: ^0.2.0

  top_up:
    path: ./packages/features/top_up

  network:
    path: ./packages/core/network

  di:
    path: ./packages/core/di

  persistence:
    path: ./packages/core/persistence

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
