name: top_up
description: TopUp created using the package template
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^0.2.0

  di:
    path: ../../core/di

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
