name: network
description: The common network logic
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.3.0

  di:
    path: ../di

  persistence:
      path: ../../core/persistence

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
